/* do not change this file, it is auto generated by storybook. */

console.log('📚 [Storybook Requires] Début du chargement de storybook.requires.ts...');

import { start, updateView } from '@storybook/react-native';

console.log('📚 [Storybook Requires] Imports de @storybook/react-native OK');

import '@storybook/addon-ondevice-controls/register';
// Note: @storybook/addon-ondevice-actions retiré car il génère un preview inexistant

console.log('📚 [Storybook Requires] Addons enregistrés');

const normalizedStories = [
  {
    titlePrefix: '',
    directory: './.rnstorybook/stories',
    files: '**/*.stories.?(ts|tsx|js|jsx)',
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-ignore
    req: require.context(
      './stories',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  },
];

declare global {
  var view: ReturnType<typeof start>;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require('./preview'),
  require('@storybook/react-native/dist/preview'),
  // Note: @storybook/addon-ondevice-actions n'a pas de fichier preview
  // Il est enregistré via register.js qui est déjà importé au-dessus
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

console.log('📚 [Storybook Requires] Initialisation de Storybook...');
console.log('📚 [Storybook Requires] normalizedStories:', normalizedStories.length, 'entries');
console.log('📚 [Storybook Requires] annotations:', annotations.length, 'entries');

try {
  if (!global.view) {
    console.log('📚 [Storybook Requires] Création de global.view...');
    global.view = start({
      annotations,
      storyEntries: normalizedStories,
    });
    console.log('✅ [Storybook Requires] global.view créé');
  } else {
    console.log('📚 [Storybook Requires] Mise à jour de global.view...');
    updateView(global.view, annotations, normalizedStories);
    console.log('✅ [Storybook Requires] global.view mis à jour');
  }
} catch (error) {
  console.error("❌ [Storybook Requires] Erreur lors de l'initialisation:", error);
  if (error instanceof Error) {
    console.error('❌ [Storybook Requires] Error type:', error.constructor.name);
    console.error('❌ [Storybook Requires] Error message:', error.message);
    console.error('❌ [Storybook Requires] Error stack:', error.stack);
  }
  throw error;
}

export const view = global.view;
